name: obd2_diagnostics_tool
description: A cross-platform OBD-II diagnostics and programming tool
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.8
  flutter_adaptive_scaffold: ^0.1.9
  adaptive_theme: ^3.6.0
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # OBD-II Communication
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1
  usb_serial: ^0.5.0
  
  # Data handling
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  
  # Platform specific
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  
  # Utilities
  intl: ^0.19.0
  logging: ^1.2.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  test: ^1.25.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

# Platform-specific configurations
flutter:
  platforms:
    android:
      default_package: obd2_diagnostics_tool
    ios:
      default_package: obd2_diagnostics_tool
    linux:
      default_package: obd2_diagnostics_tool
    macos:
      default_package: obd2_diagnostics_tool
    windows:
      default_package: obd2_diagnostics_tool
    web:
      default_package: obd2_diagnostics_tool