name: new_obd2_tool
description: A Flutter-based OBD-II Diagnostics and Programming Tool.
publish_to: 'none'

version: 1.3.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_bluetooth_serial: ^0.4.0           # Mobile Bluetooth
  serial_port_win32: ^2.2.0                  # Windows Serial port
  http: ^1.2.1
  dio: ^5.4.3
  provider: ^6.1.2
  flutter_riverpod: ^2.4.9                   # Advanced state management
  riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  file_picker: ^10.2.0
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.41
  syncfusion_flutter_gauges: ^30.1.41
  responsive_framework: ^1.1.1
  flutter_screenutil: ^5.9.0
  # TODO: Security enhancements for connection profile encryption
  crypto: ^3.0.3                             # For secure hashing and encryption
  flutter_secure_storage: ^9.0.0            # Secure storage for sensitive data
  # Version 1.1 enhancements
  csv: ^6.0.0                                # Data export functionality
  archive: ^4.0.7                          # For compressed exports
  universal_html: ^2.2.4                    # Web-compatible HTML manipulation
  json_annotation: ^4.9.0                   # JSON serialization
  intl: ^0.20.2                              # Internationalization and date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  json_serializable: ^6.8.0               # JSON code generation

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/data/strings/
    - assets/icons/
    - assets/images/